### ISSUE TITLE
Heigt Error when creating a TIF from LAS files.

### ISSUE THREAD

**Issue by salmagro** [biglimp/qgis-fusion#1]
I am using the plugging Fusion with QGIS 3.6.3, in order to create a MDT (gray scale raster with heights) based on a LAS File (22x10^6 points).

The pipeline that I am using is:
1. FUSION>Surface>Tin surface create. Tested with "Cellsize = 0.01m" 
The visualization of the resultant DEM is:
![image](https://user-images.githubusercontent.com/52298571/63370799-33480200-c383-11e9-9d6c-cd4fb7aceb4e.png)

2. FUSION>Conversion>DTM to TIF
![image](https://user-images.githubusercontent.com/52298571/63370966-7efaab80-c383-11e9-8d82-41f9e29573c5.png)

The resulting TIF does not have the height values of the original LAS file. The Z values have an Offset and a scaling factor.

In which step my model is being distorted? Which settings I am no considering during the conversion.

Thank you very much for your help.

**Comment by biglimp** [comment]
Please consult the FUSION manual (http://forsys.cfr.washington.edu/Software/FUSION/FUSION_manual.pdf) for info on DTM2TIF. Suggestion to you is to make use of DTM2ASCII to preserve height infromation.

**Comment by salmagro** [comment]
Thank you very much for your clarification. I used the tool DTM2ASCII and worked perfectly.
