### ISSUE TITLE
General Issue

### ISSUE THREAD

**Issue by charles9469** [biglimp/qgis-fusion#10]
Hello,

I'm unable to run any algorithm on QGIS.

Is LAStool software mandatory ?

![image](https://user-images.githubusercontent.com/8075710/154083771-44a139d2-12cf-4528-9ee9-70bec0794f14.png)

____________________________________________________________________________
Version de QGIS : 3.22.3-Białowieża
Révision du code : 1628765ec7
Version de Qt : 5.15.2
Version de Python : 3.9.5
Version de GDAL : 3.4.1
Version de GEOS : 3.10.0-CAPI-1.16.0
Version de Proj : Rel. 8.2.1, January 1st, 2022
Version de PDAL : 2.3.0 (git-version: 9f35b7)
Algorithme commencé à: 2022-02-15T15:37:47
Démarrage de l'algorithme 'Canopy model'…
Paramètres en entrée:
{ 'ADVANCED_MODIFIERS' : '', 'ASCII' : False, 'CELLSIZE' : 10, 'CLASS' : '', 'GROUND' : '', 'INPUT' : 'C:\\Users\\clopez\\Downloads\\Semis_2021_0784_6289_LA93_IGN69.laz', 'MEDIAN' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'SLOPE' : False, 'SMOOTH' : '', 'VERSION64' : True, 'XYUNITS' : 0, 'ZUNITS' : 0 }

FUSION command:
CanopyModel64.exe /verbose "C:/Users/clopez/AppData/Local/Temp/processing_zuZRwN/a5613f1389754707b09bde8b5776c334/OUTPUT.dtm" 10.0 M M 0 0 0 0 "C:\Users\clopez\Downloads\Semis_2021_0784_6289_LA93_IGN69.laz"
FUSION command output:
Execution completed in 0.09 secondes
Résultats :
{'OUTPUT': 'TEMPORARY_OUTPUT'}

Chargement des couches de résultat
Algorithme 'Canopy model' terminé

**Comment by biglimp** [comment]
LASTools is needed if you have .laz-files. See http://forsys.sefs.uw.edu/fusion/fusionlatest.html on how to activate reading of laz-files. You can also convert to .las-files which can be read by FUSION without any extra dll-files.
