### ISSUE TITLE
Can't run plugin

### ISSUE THREAD

**Issue by frnmz** [biglimp/qgis-fusion#12]
Hi thanks for your great software!
But I can't run the tools from qgis toolbox.
It's always says:
```
FUSION command:
C:/Program Files/FUSION\GroundFilter64.exe "C:/Users/Farhan/AppData/Local/Temp/processing_QdAsjJ/dc6e0b1dbb21475680468ce7befd6c4d/OUTPUT.las" 10.0 "C:\Users\Farhan\Downloads\points.las"
FUSION command output:
'C:/Program' is not recognized as an internal or external command,

operable program or batch file.
```
I already install Fusion, and setting it in the processing providers:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/18339774/164974004-228a36d4-a2c0-41ba-adad-f9188d02e1ab.png">

**Comment by biglimp** [comment]
Try installing FUSION in C:\FUISION instead.

**Comment by frnmz** [comment]
It does work when installed in C:\FUISION
I think it's because the first command doesn't use double quote(")?
so instead of:
`C:/Program Files/FUSION\GroundFilter64.exe`
it should be:
`"C:/Program Files/FUSION\GroundFilter64.exe"`

**Comment by biglimp** [comment]
should be fixed now.
