### ISSUE TITLE
Ascii2dtm calls polyclipdata so it does not work

### ISSUE THREAD

**Issue by JaimeGeoPi** [biglimp/qgis-fusion#13]
Hi,
First of all. Thanksfor your work.

The issue I have just found is that trying to run ascii2dtm withou any output I have read the log messages and it seem that ascii2dtm is calling polyclipdata and it ends to no result.

Kind regards,
Jaime

**Comment by biglimp** [comment]
Thanks. It might take some time (hours to days) before the new version (3.4) appear in the QGIS plugin repo.
