### ISSUE TITLE
[FUSION/LDV] GridMetrics doesn't show up in QGIS

### ISSUE THREAD

**Issue by spono** [biglimp/qgis-fusion#2]
Hi,
I'm using your plugin on QGIS 3.10 but a (pretty useful) tool such as _GridMetrics_ doesn't appear listed in the Processing window.
I checked among your files and it seems to be present in your repo: do you have any idea why this may happen?
Thanks in advance

**Comment by biglimp** [comment]
I was coded but not added from the beginning. I think it should work now. Use the latest commit (version 1.2) from this repo. I will update QGIS plugin repo later.
