### ISSUE TITLE
Unable to input multiple files to canopymodel

### ISSUE THREAD

**Issue by bweeding** [biglimp/qgis-fusion#9]
Hi all, would be great to be able to input multiple las files in the canopy model processing tool. Can be done in python as follows:

processing.run("fusion:canopymodel",{'version64':True, 
                "INPUT":"C:/Users/weedingb/Desktop/Learning_LAStools/veg_outside_buildings.las;C:/Users/weedingb/Desktop/Learning_LAStools/ground.las", 
                "CELLSIZE":1, 
                "XYUNITS":0, 
                "ZUNITS":0, 
                "OUTPUT":"C:/Users/weedingb/Desktop/Learning_LAStools/test.dtm"})

**Comment by biglimp** [comment]
I agree. This is a limitation we are aware of (https://github.com/biglimp/qgis-fusion#known-limitations) but to fix this, the core function used in QGIS must be altered. You could submit a feature request or a regular issue to the main QGIS repository and see what the status is on this matter.

**Comment by bweeding** [comment]
Ah so it couldn't be done by inserting an optional second file choice?

**Comment by biglimp** [comment]
No, but you can paste search path manually if you want multiple files as input.
